name: flutter_colorize
description: Collection of 1000 + pre-loaded colors for Flutter.
version: 1.0.0

homepage: https://github.com/JonathanMonga/flutter_colorize

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
